common:
    lid_topic:  "/os1_points"
    imu_topic:  "/imu/data_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 6               # 在 preprocess.h 的枚举里：AVIA=1, VELO16=2, OUSTER=3, HESAI128=4, XGRIDS=5。所以我们新加的 OUSTER_MULRAN 应该是 6。
    scan_line: 64
    blind: 4

mapping:
    acc_cov: 0.0001
    gyr_cov: 0.08
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     150.0
    extrinsic_T: [ 1.77, 0.06, -0.05 ]
    extrinsic_R: [-1, 0, 0,
                  0, -1, 0,
                  0, 0, 1]

publish:
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: true       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame
